---
namespace: kravietz
name: wpa_supplicant
version: 1.0.0
readme: README.md
authors:
- Pawel Krawczyk (https://krvtz.net/)

description: Role for wpa_supplicant management and configuration with all options and systemd support.

license_file: 'LICENSE'

tags:
    - hostapd
    - wifi
    - wpa_supplicant
    - linux

dependencies: {}

repository: https://github.com/kravietz/wpa_supplicant/
documentation: https://github.com/kravietz/wpa_supplicant/
homepage: https://github.com/kravietz/wpa_supplicant/
issues: https://github.com/kravietz/wpa_supplicant//issues
